export const AUTH_START = 'AUTH_START'

export const AUTH_SIGINUP_SUCCESS = 'AUTH_SIGINUP_SUCCESS'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'

export const AUTH_RESET_STATE = 'AUTH_RESET_STATE'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REDIRECT = 'AUTH_REDIRECT'



export const CHECK_USER = 'CHECK_USER'
export const SET_PATH = 'SET_PATH'


